drop table LOAN;
drop table ACCOUNT;
drop table CUSTOMER;
drop table BRANCH;

CREATE TABLE BRANCH(
   BRANCH_ID      NUMBER(12) NOT NULL,
   BRANCH_CITY    VARCHAR2(15),
   BRANCH_NAME	  VARCHAR2(15) NOT NULL,
   ASSET          NUMBER(12),
   CONSTRAINT BRANCH_PK PRIMARY KEY (BRANCH_ID)
);


CREATE TABLE CUSTOMER (
   CUSTOMER_ID     NUMBER(12) NOT NULL,
   NAME            VARCHAR2(15),
   ADDRESS         VARCHAR2(35),
   SEX             VARCHAR2(6),
   PHONE_NUMBER    NUMBER(12) NOT NULL,
   BRANCH_ID       NUMBER(12) NOT NULL
);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT FK_BRANCH_CUSTOMER FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (BRANCH_ID) ON DELETE CASCADE;


CREATE TABLE ACCOUNT (
 ACCOUNT_NO             NUMBER(12) NOT NULL,
 BALANCE                NUMBER(12) CHECK (BALANCE >= 500),
 CUSTOMER_ID            NUMBER(12)
);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_NO);
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_CUS_ACCOUNT FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE;


CREATE TABLE LOAN (
 LOAN_NUMBER            NUMBER(12) NOT NULL,
 AMOUNT         		NUMBER(10),
 LOAN_DATE              DATE DEFAULT SYSDATE,
 CUSTOMER_ID            NUMBER(12) UNIQUE NOT NULL,
 PRIMARY KEY (LOAN_NUMBER)
);
ALTER TABLE LOAN ADD CONSTRAINT PK_LOAN FOREIGN KEY (LOAN_NUMBER);
ALTER TABLE LOAN ADD CONSTRAINT FK_CUS_LOAN FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE;

SELECT * FROM TAB;

DESCRIBE LOAN;
DESCRIBE ACCOUNT;
DESCRIBE CUSTOMER;
DESCRIBE BRANCH;

INSERT INTO BRANCH VALUES (333445555, 'DHAKA', 'GULSAN-1', 22000000);
INSERT INTO BRANCH VALUES (333445556, 'DHAKA', 'DHANMONDI', 12000000);
INSERT INTO BRANCH VALUES (333445557, 'BOGRA', 'BOGRA SADAR', 13000000);
INSERT INTO BRANCH VALUES (333445558, 'DHAKA', 'UTTARA', 14000000);

INSERT INTO CUSTOMER VALUES (1234560, 'KAMAL', 'GULSAN-1', 'MALE', 01711123456, 333445555);
INSERT INTO CUSTOMER VALUES (1234561, 'JAMAL', 'GULSAN-2', 'MALE', 01711123457, 333445556);
INSERT INTO CUSTOMER VALUES (1234562, 'RIMA', 'GULSAN-1', 'FEMALE', 01711123458, 333445557);

INSERT INTO ACCOUNT VALUES (123450, 500, 1234560);
INSERT INTO ACCOUNT VALUES (123451, 1000, 1234561);
INSERT INTO ACCOUNT VALUES (123452, 2000, 1234562);

INSERT INTO LOAN (LOAN_NUMBER, AMOUNT, CUSTOMER_ID) VALUES (1230, 1000, 1234560);
INSERT INTO LOAN (LOAN_NUMBER, AMOUNT, CUSTOMER_ID) VALUES (1231, 1000, 1234561);
INSERT INTO LOAN (LOAN_NUMBER, AMOUNT, CUSTOMER_ID) VALUES (1232, 1000, 1234562);

SELECT * FROM BRANCH;
SELECT * FROM CUSTOMER;
SELECT * FROM ACCOUNT;
SELECT * FROM LOAN;

SELECT B.BRANCH_NAME, C.NAME FROM BRANCH B NATURAL JOIN CUSTOMER C;
SELECT C.NAME, A.BALANCE FROM CUSTOMER C NATURAL JOIN ACCOUNT A;
SELECT C.NAME, L.AMOUNT FROM CUSTOMER C NATURAL JOIN LOAN L;

SELECT DISTINCT (ACCOUNT) FROM ACCOUNT;

DELETE FROM BRANCH WHERE BRANCH_ID = 333445555;




















